packages:
  - playground

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - simple-git-hooks


overrides:
  "@nuxt/kit": "^4.0.0"
  "@nuxtjs/fontaine": "link:."
